version: '3.8'
services:
  api:
    build:
      context: ./VendePraMim.Api
      dockerfile: Dockerfile
    image: vendepra.api
    container_name: vendepra_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  blazor:
    build:
      context: ./VendePraMim.Blazor
      dockerfile: Dockerfile
    image: vendepra.blazor
    container_name: vendepra_blazor
    ports:
      - "5001:80"
    depends_on:
      - api
